// Generated by CoffeeScript 1.9.2

/*!
 * @license partition-size
 * (c) sugarshin
 * License: MIT
 */

(function() {
  "use strict";
  var partition, partitionSize;

  partition = require('lodash.partition');

  module.exports = partitionSize = (function() {
    var _partitionSize;
    return _partitionSize = function(array, point, result, n) {
      var _n, _result;
      if (array.length <= point) {
        return array;
      }
      if (result != null) {
        _result = result;
        _result.pop();
        partition(array, function(el, i, array) {
          return i < point;
        }).forEach(function(el, i) {
          return _result.push(el);
        });
      } else {
        _result = partition(array, function(el, i, array) {
          return i < point;
        });
      }
      if (n != null) {
        _n = n + 1;
      } else {
        _n = 1;
      }
      if (_result[_n].length > point) {
        return _partitionSize(_result[_n], point, _result, _n);
      } else {
        return _result;
      }
    };
  })();

}).call(this);
