// Generated by CoffeeScript 1.9.2

/*!
 * @license partition-size
 * (c) sugarshin
 * License: MIT
 */

(function() {
  "use strict";
  var partition, partitionSize;

  partition = require('lodash.partition');

  module.exports = partitionSize = (function() {
    var _partitionSize;
    return _partitionSize = function(array, point, result, n) {
      if (array.length <= point || 0 >= point) {
        return array;
      }
      if (result != null) {
        result.pop();
        partition(array, function(el, i, array) {
          return i < point;
        }).forEach(function(el, i) {
          return result.push(el);
        });
      } else {
        result = partition(array, function(el, i, array) {
          return i < point;
        });
      }
      if (n != null) {
        n++;
      } else {
        n = 1;
      }
      if (result[n].length > point) {
        return _partitionSize(result[n], point, result, n);
      } else {
        return result;
      }
    };
  })();

}).call(this);
